<?php
/**
 * Copyright © Samdoit (support@samdoit.com). All rights reserved.
 * Please visit Samdoit.com for license details (https://www.samdoit.com/end-user-license-agreement).
 */

/** @var $block \Samdoit\GoogleAnalytics\Block\GoogleAnalytics */
/** @var \Magento\Framework\Escaper $escaper */

$analyticsData = $block->getAnalyticsData();
?>

<?php if ($analyticsData): ?>
    <!-- BEGIN GOOGLE ANALYTICS 4 CODE -->
    <script type="text/x-magento-init">
    {
        "*": {
            "Samdoit_GoogleAnalytics/js/google-analytics": <?= /* @noEscape */ $block->getAnalyticsData() ?>
        }
    }
    </script>
    <!-- END GOOGLE ANALYTICS 4 CODE -->
<?php endif; ?>
