<?php
/**
 * Copyright © Samdoit (support@samdoit.com). All rights reserved.
 * Please visit Samdoit.com for license details (https://www.samdoit.com/end-user-license-agreement).
 */
/** @var \Samdoit\GoogleAnalytics\Block\Adminhtml\System\Config\Form\EventList $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<?php
$events = [
    'All Page View (page_view)',
    'Checkout Success Page (purchase)'
];
$eventsPlus = [
    'View Product (view_item)',
    'View Shopping Cart (view_cart)',
    'View Checkout (begin_checkout)',
    'Add To Cart (add_to_cart)',
    'Remove From Cart (remove_from_cart)',
    'Add To Wishlist (add_to_wishlist)',
    'View Product List on category page, related/up-sell/cross-sell products (view_item_list)',
    'Shipping Step on Checkout Page (add_shipping_info)',
    'Payments Step on Checkout Page (add_payment_info)',
    'Google Ads - Conversion Tracking',
    'Google Ads - Dynamic Remarketing',
    'Sign In (login)',
    'Create an Account (sign_up)',
    'Search (search)',
    /*
    'Earn Virtual Currency (earn_virtual_currency)',
    'Spend Virtual Currency (spend_virtual_currency)'
    */
];
?>
<br/>
<div>
    <ul>
        <li>
            <?= implode('</li><li>', $events) ?>
        </li>
    </ul>
    <p <?php if (!$block->isPlusEnabled()) { ?>style="color: #eb5202"<?php } ?>>
        <strong>
            <?= $escaper->escapeHtml(__(!$block->isPlusEnabled() ? 'Available in GTM Plus Only' : 'GTM Plus')) ?>
            <?php if (!$block->isPlusEnabled()) { ?>
                (<a style="color: #eb5202; text-decoration: underline;" href="https://www.samdoit.com" target="_blank">Read more</a>):
            <?php } ?>
        </strong>
    </p>
    <div <?php if (!$block->isPlusEnabled()) { ?>style="opacity: 0.7; color: #eb5202"<?php } ?>>
        <ul>
            <li>
                <?= implode('</li><li>', $eventsPlus) ?>
            </li>
        </ul>
    </div>
    <?php if (!$block->isPlusEnabled()) { ?>
    <button title="Upgrade" type="button" class="primary" onclick="window.open('https://www.samdoit.com')">
        <span>Upgrade to Google Analytics Plus</span>
    </button>
    <?php } ?>
</div>
