<?php
/**
 * Copyright © Samdoit (support@samdoit.com). All rights reserved.
 * Please visit Samdoit.com for license details (https://www.samdoit.com/end-user-license-agreement).
 */
/** @var \Samdoit\GoogleAnalytics\Block\Adminhtml\System\Config\Form\EventList $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<?php
$events = [
    'All Page View (page_view)',
    'Checkout Success Page (purchase)',
    'View Product List on category page, related/up-sell/cross-sell products (view_item_list)',
];
$eventsPlus = [
    'View Product (view_item)',
    'View Shopping Cart (view_cart)',
    'View Checkout (begin_checkout)',
    'Add To Cart (add_to_cart)',
    'Remove From Cart (remove_from_cart)',
    'Add To Wishlist (add_to_wishlist)',
    'Sign In (login)',
    'Create an Account (sign_up)',
    'Search (search)'
];
$contntDisplay = [
    'Available in Google Analytics 4 Plus Only',
    'Google Analytics 4 Plus',
    'https://www.samdoit.com/google-analytics-4-plus.html',
    'color: #eb5202; text-decoration: underline;'
];
?>
<br/>
<div>
    <ul>
        <?php foreach ($events as $event): ?>
            <li><?= $escaper->escapeHtml($event) ?></li>
        <?php endforeach; ?>
    </ul>
    <p <?php if (!$block->isPlusEnabled()) { ?>style="color: #eb5202"<?php } ?>>
        <strong>
            <?= $escaper->escapeHtml(__($block->isPlusEnabled() ? $contntDisplay[1] : $contntDisplay[0])) ?>
        </strong>
    </p>
    <div <?php if (!$block->isPlusEnabled()) { ?>style="opacity: 0.7; color: #eb5202"<?php } ?>>
        <ul>
            <?php foreach ($eventsPlus as $event): ?>
                <li><?= $escaper->escapeHtml($event) ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php if (!$block->isPlusEnabled()) { ?>
    <button title="Upgrade" type="button" class="primary"
        onclick="window.open('<?= $escaper->escapeUrl($contntDisplay[2]) ?>', '_blank');">
        <span>Upgrade to Google Analytics 4 Plus</span>
    </button>
    <?php } ?>
</div>
